[package]
name = "dbvh"
version = "0.1.2"
edition = "2024"
license = "0BSD"
description = "A dynamic bvh using generic bounding volume with 0 dependencies"
repository = "https://github.com/newDINO/dbvh"

[dependencies]


[dev-dependencies]
rand = "0.10"
rand_chacha = "0.10"
nalgebra = { version = "0.35", features = ["convert-glam033"] }
glam = "0.33"

criterion = "0.8"

[[bench]]
name = "intersection"
harness = false

[[bench]]
name = "spawn"
harness = false

[[bench]]
name = "sphere"
harness = false

[[bench]]
name = "ray_cast"
harness = false
